# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  
    # The Lint job: Runs Clang-Tidy
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      
      # install Clang-Tidy (and clang)
      - name: Install Clang-Tidy
        run: |
          if ! command -v clang-tidy &> /dev/null; then
            echo "clang-tidy not found. Installing..."
            sudo apt-get update
            sudo apt-get install -y clang-tidy
          else
            echo "clang-tidy already installed."
            clang-tidy --version
          fi
      # configure CMake to generate compile_commands.json
      - name: Configure CMake for Clang-Tidy
        run: cmake -B ${{github.workspace}}/build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_DOXYGEN_TARGET=OFF

      # run Clang-Tidy (replace 'my_project_target' with your actual target name or use a script)
      - name: Run Clang-Tidy
        # working directory is root as default
        run: |
          find ${{github.workspace}}/src -name "*.cpp" | xargs clang-tidy -p ${{github.workspace}}/build -config-file=.clang-tidy -warnings-as-errors='*' --quiet
      
  build-and-test:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build \
        -DENABLE_DOXYGEN_TARGET=OFF \ 
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        -DCMAKE_CXX_FLAGS="-fsanitize=address -g"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
 
    - name: Run Google Tests with sanitize
      working-directory: ${{github.workspace}}/build
      env:
        # set ASAN to detect memory leaks
        ASAN_OPTIONS: detect_leaks=1
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      # execute ctests and output if tests fail
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
  

